#!/usr/bin/env bash
#
#    ^   ||''\ ||''| ['|']
#   //\  ||--< ||-     |  
#  //''\ ||__/ ||__|  .|  
#
# Description:              Yet another Ascii alphaBET
# Dependencies:             pure
# Optionnal dependencies:   none
# Author:                   gawlk
# Contributors:             none

# ---
# IMPORTS
# ---

. pure

# ---
# A
# ---
#
#   ^
#  //\
# //''\

abet.a() {
    local line0="   ^  "
    local line1="  //\\ "
    local line2=" //''\\"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# B
# ---
#
# ||''\
# ||--<
# ||__/

abet.b() {
    local line0=" ||''\\"
    local line1=" ||--<"
    local line2=" ||__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# C
# ---
#
#  //'.
# ||   
#  \\_/

abet.c() {
    local line0="  //'."
    local line1=" ||   "
    local line2="  \\\\_/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# D
# ---
#
# ||'\
# ||  |
# ||_/

abet.d() {
    local line0=" ||'\\ "
    local line1=" ||  |"
    local line2=" ||_/ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# E
# ---
#
# ||''|
# ||-
# ||__|

abet.e() {
    local line0=" ||''|"
    local line1=" ||-  "
    local line2=" ||__|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# F
# ---
#
# ||''|
# ||-
# ||

abet.f() {
    local line0=" ||''|"
    local line1=" ||-  "
    local line2=" ||   "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# G
# ---
#
#  //'|
# ||  _
#  \\_/

abet.g() {
    local line0="  //'|"
    local line1=" ||  _"
    local line2="  \\\\_/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# H
# ---
#
# ||  |
# ||--|
# ||  |

abet.h() {
    local line0=" ||  |"
    local line1=" ||--|"
    local line2=" ||  |"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# I
# ---
#
# '||'
#  ||
# .||.

abet.i() {
    local line0=" '||' "
    local line1="  ||  "
    local line2=" .||. "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# J
# ---
#
# |''|'
#    |
# \\_/

abet.j() {
    local line0=" |''|'"
    local line1="    | "
    local line2=" \\\\_/ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# K
# ---
#
#  || /
#  ||x
# .|| \

abet.k() {
    local line0="  || /"
    local line1="  ||x "
    local line2=" .|| \\"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# L
# ---
#
# '||  
#  || 
#  ||_|

abet.l() {
    local line0=" '||  "
    local line1="  ||  "
    local line2="  ||_|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# M 
# ---
#
# ||\/|
# ||  |
# ||  |

abet.m() {
    local line0=" ||\\/|"
    local line1=" ||  |"
    local line2=" ||  |"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# N
# ---
#
# |\  |
# ||\ |
# || \|

abet.n() {
    local line0=" |\\  |"
    local line1=" ||\\ |"
    local line2=" || \\|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# O
# ---
#
#  //\ 
# ||  |
#  \\/

abet.o() {
    local line0="  //\\ "
    local line1=" ||  |"
    local line2="  \\\\/ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# P
# ---
#
# ||''.
# ||--'
# ||

abet.p() {
    local line0=" ||''."
    local line1=" ||--'"
    local line2=" ||   "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# Q
# ---
#
#  //\ 
# ||  |
#  \\X_

abet.q() {
    local line0="  //\\ "
    local line1=" ||  |"
    local line2="  \\\\X_"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# R
# ---
#
# ||''.
# ||-+'
# ||  \

abet.r() {
    local line0=" ||''."
    local line1=" ||-+'"
    local line2=" ||  \\"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# S
# ---
#
# //''\
# ``--.
# \\__/

abet.s() {
    local line0=" //''\\"
    local line1=" \`\`--."
    local line2=" \\\\__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# T
# ---
#
# ['|']
#   |
#  .|

abet.t() {
    local line0=" ['|']"
    local line1="   |  "
    local line2="  .|  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# U
# ---
#
# ||  |
# ||  |
# `\__'

abet.u() {
    local line0=" ||  |"
    local line1=" ||  |"
    local line2=" \`\\__'"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# V
# ---
#
# \\  /
#  \\/
#   V

abet.v() {
    local line0=" \\\\  /"
    local line1="  \\\\/ "
    local line2="   V  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# W
# ---
#
# ||  |
# ||  |
# ||/\|

abet.w() {
    local line0=" ||  |"
    local line1=" ||  |"
    local line2=" ||/\\|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# X
# ---
#
# '\ //
#   X/
# _//\_

abet.x() {
    local line0=" '\\ //"
    local line1="   X/ "
    local line2=" _//\\_"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# Y
# ---
#
# \\ /'
#   V
#  .|

abet.y() {
    local line0=" \\\\ /'"
    local line1="   V  "
    local line2="  .|  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# Z
# ---
#
# ''//
#  //
# //__.

abet.z() {
    local line0=" ''// "
    local line1="  //  "
    local line2=" //__."
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# 0
# ---
#
#  //\ 
# ||//|
#  \\/

abet.0() {
    local line0="  //\\ "
    local line1=" ||//|"
    local line2="  \\\\/ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}
# ---
# 1
# ---
#
# /||
#  ||
# _||_

abet.1() {
    local line0=" /||  "
    local line1="  ||  "
    local line2=" _||_ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# 2
# ---
#
#  /'X\
# ` //
#  //__

abet.2() {
    local line0=" /'X\\ "
    local line1="  //  "
    local line2=" //__ "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# 3
# ---
#
# //''\
#    -<
# \\__/

abet.3() {
    local line0=" //''\\"
    local line1="    -<"
    local line2=" \\\\__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# 4
# ---
#
#  //|
# //_|_
#   ||

abet.4() {
    local line0="  //| "
    local line1=" //_|_"
    local line2="   || "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# 5
# ---
#
# ||'''
# `'--.
# \\__/

abet.5() {
    local line0=" ||'''"
    local line1=" \`'--."
    local line2=" \\\\__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}


# ---
# 6
# ---
#
#  //''
# ||--.
#  \\_/

abet.6() {
    local line0="  //''"
    local line1=" ||--."
    local line2="  \\\\_/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# 7
# ---
#
# \''//
#   //
#  //

abet.7() {
    local line0=" \\''//"
    local line1="   // "
    local line2="  //  "
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# 8
# ---
#
# //''\
# >>--<
# \\__/

abet.8() {
    local line0=" //''\\"
    local line1=" >>--<"
    local line2=" \\\\__/"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# 9
# ---
#
# //''|
# ``--|
# \\__|

abet.9() {
    local line0=" //''|"
    local line1=" \`\`--|"
    local line2=" \\\\__|"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# .
# ---
#
#
# o

abet.dot() {
    local line0="  "
    local line1="  "
    local line2=" o"
    printf '%s\n%s\n%s' "$line0" "$line1" "$line2"
}

# ---
# MAIN
# ---

abet.main() {
    local string="$( pure.lower "$1" )"

    local char

    local line0
    local line1
    local line2

    local oldIFS

    local ascii_char

    if [[ -n "$string" ]]
    then
        for (( i=0; i < ${#string}; i++ ))
        do
            char="${string:$i:1}"

            case "$char" in
                [a-z] | [0-9])
                    oldIFS=$IFS
                    IFS=$'\n'

                    ascii_char=( $( abet."$char" ) )
                    
                    line0+="${ascii_char[0]}"
                    line1+="${ascii_char[1]}"
                    line2+="${ascii_char[2]}"

                    IFS=$oldIFS
                ;;
                ".")
                    oldIFS=$IFS
                    IFS=$'\n'

                    ascii_char=( $( abet.dot ) )
                    
                    line0+="${ascii_char[0]}"
                    line1+="${ascii_char[1]}"
                    line2+="${ascii_char[2]}"

                    IFS=$oldIFS
                ;;
                " ")
                    line0+="    "
                    line1+="    "
                    line2+="    "
                ;;
            esac
        done

        printf '\n %s\n %s\n %s\n\n' "$line0" "$line1" "$line2"
    fi
}

# ---
# LAUNCH
# ---

abet.main "$*"
