#!/usr/bin/env bash
#
# Description: Display an alert based on it's importance
# Dependency: wget

# Set to null
var="null"

# Check if internet
wget -q --spider http://google.com || var="noip"

echo "! $var"
