#!/usr/bin/env bash
#
#  ||''\ ||''. '||'  ['|']
#  ||--< ||-+'  ||     |  
#  ||__/ ||  \ .||.   .| 
#
# Description:              A minimal brightness manager
# Dependencies:             xbacklight
# Optionnal dependencies:   notf
# Author:                   gawlk
# Contributors:             none

# ---
# SETUP
# ---

IFS=$'\n'
ps=( $( ps -ax | grep "brit" ) )

# ---
# LOCAL
# ---

brit.args() {
    local current=$( brit.current )

    case "$1" in
        "+" | "inc" )
            if [[ $current -le 2 ]]
            then
                xbacklight -set 5
            elif [[ $current -le 15 ]]
            then
                xbacklight -inc 5
            elif [[ $current -le 50 ]]
            then
                xbacklight -inc 10
            elif [[ $current -ge 60 ]]
            then
                xbacklight -inc 20
            fi
        ;;
        "-" | "dec" )
            if [[ $current -le 5  ]]
            then
                xbacklight -set 2
            elif [[ $current -gt 60 ]]
            then
                xbacklight -dec 20
            elif [[ $current -gt 20 ]]
            then
                xbacklight -dec 10
            elif [[ $current -gt 5 ]]
            then
                xbacklight -dec 5
            fi
        ;;
        "=" | "rst" )
            xbacklight -set 30
        ;;
    esac
}

brit.current() {
    local value=$(xbacklight -get)
    printf '%d\n' "${value%.*}"
}

brit.get_percentage() {
    local current=$( brit.current )
    local percentage

    if [[ $current == 2 ]]
    then
        percentage=0
    elif [[ $current -le 20 ]]
    then
        percentage=$(( ( current / 5 ) * 10 ))
    elif [[ $current -le 60 ]]
    then
        percentage=$(( current + 20 ))
    elif [[ $current == 80 ]]
    then
        percentage=90
    elif [[ $current -gt 80 ]]
    then
        percentage=$current
    fi

    printf '%d\n' "$percentage"
}

# ---
# MAIN
# ---

brit.main() {
    brit.args "$1"

    local message="Brightness: $( brit.get_percentage )%"

    notf "$message" &> /dev/null || printf '%s\n' "$message"
}

# ---
# LAUNCH
# ---

# Only if no other instance of brit is already executed
[[ ${#ps[@]} -lt 4 ]] && brit.main "$1"
