#!/usr/bin/env bash
#
# Description: Display the color palette 

# Set the location of the file containing colors
colors="${HOME}/.colors"

# Get parameters
[[ -n "$1" && "$1" == "-q" ]] && quiet="true"

# If file doesn't exist, abort
[ ! -f $colors ] && echo "Please create a theme first" && exit 1

# Get hexadical values
xblk=`cat $colors | grep blk | awk '{ print $3 }'`
xgry=`cat $colors | grep gry | awk '{ print $3 }'`
xred=`cat $colors | grep red | awk '{ print $3 }'`
xgrn=`cat $colors | grep grn | awk '{ print $3 }'`
xblu=`cat $colors | grep blu | awk '{ print $3 }'`
xwht=`cat $colors | grep wht | awk '{ print $3 }'`

# Background
bwht="\e[40m"
bgry="\e[100m"
bred="\e[41m"
bgrn="\e[42m"
bblu="\e[44m"
bblk="\e[47m"

# Foreground
fwht="\e[37m"
fgry="\e[90m"
fred="\e[31m"
fgrn="\e[32m"
fblu="\e[34m"
fblk="\e[30m"

clear 

echo -e "\n"
echo -en "         ${bgry}         ${bred}         ${bgrn}         ${bblu}         ${bblk}         ${bwht}\n"
echo -en "         ${bgry}         ${bred}         ${bgrn}         ${bblu}         ${bblk}         ${bwht}\n"
echo -en "         ${bgry}         ${bred}         ${bgrn}         ${bblu}         ${bblk}         ${bwht}\n"
echo -en "         ${bgry}         ${bred}         ${bgrn}         ${bblu}         ${bblk}         ${bwht}\n"
[[ "$quiet" != "true" ]] && echo -en " ${xblk}  ${fgry}${xgry}  ${fred}${xred}  ${fgrn}${xgrn}  ${fblu}${xblu}  ${fwht}${xwht}\n"
echo -e "\n"

if [[ -n "$1" && "$1" == "-s" ]]
then
    sleep 0.1
    theme=`cat ${HOME}/.colors | head -1 | cut -f2 -d" "`
    scrot -u ${HOME}/.themes/${theme}/preview.png
fi
