#!/usr/bin/env bash
#
# Description: Draw a terminal using the selected area
# Dependency: slop, urxvt-unicode

read -r X Y W H < <(slop -f "%x %y %w %h" -b 1 -t 0 -q)

(( W /= 6 ))
(( H /= 15 ))

g=${W}x${H}+${X}+${Y}

urxvt -g $g
