#!/usr/bin/env bash
#
#  ||\/|  //'| |\  | ['|']
#  ||  | ||  _ ||\ |   |  
#  ||  |  \\_/ || \|  .|  
#
# Description:              A minimal magnet getter from the Pirate Bay
# Dependencies:             wget, xclip
# Optionnal dependencies:   notf
# Author:                   gawlk
# Contributors:             none

# ---
# IMPORTS
# ---

. log

# ---
# SETUP
# ---

max=10

# ---
# MAIN
# ---

mgnt.main() {
    local name=$@
    name="${name/ /%20}"
    [[ -z "$name" ]] && log.error "mgnt" "Please provide a correct name."

    local tmp="/tmp/tpb"

    log.info "mgnt" "Searching..."

    wget -O $tmp -q --timeout=20 "https://thepiratebay.org/search/${name}/0/99/0" || \
        log.error "arguments" "TPB servers are unreachable."

    [[ -n "$( cat $tmp | grep "502: Bad gateway" )" ]] && log.error "arguments" "TPB is unavailable"

    local list=( $( grep "magnet:?" < $tmp | cut -f2 -d"\"" ) )

    local magnets=( )
    local count=1

    for i in "${list[@]}"
    do
        [[ $count -gt $max ]] && break
        
        local tempo=${i##*dn=}
        tempo=$( printf '%s\n' "$tempo" | cut -f1 -d"&" )
        
        printf '%s\n' "${count}) ${tempo}"

        magnets+=( $i )

        (( count++ ))
    done

    (( count-- ))

    printf '%s\n' "Enter a number:"
    read nb

    (( nb-- ))

    printf '%s' ${magnets[$nb]} | xclip -selection c
    
    log.info "mgnt" "Magnet copied !"
}

# ---
# LAUNCH
# ---

mgnt.main "$@"
