#!/usr/bin/env bash
#
# Description: Close the last notification and display a new one
# Dependencies: dunst, libnotify, xdotool

str="$1"
[ -z "$str" ] && str="Test"

xdotool key "ctrl+space" &> /dev/null
notify-send "$str"
