#!/usr/bin/env bash
#
# Description: Sync files to git folder
# Dependency: rsync

git="${HOME}/.git"

title() {
    echo -e "\n$1\n"
}

print() {
    name=$1
    echo "Syncing ${name}..."
}

sync() {
    rsync -r ${HOME}/.${name}/ ${git}/${name} &> /dev/null
    [ $? -ne 0 ] && echo "ERROR: ~/${HOME}/.${name} doesn't exist" && return 0
}

sync_dots() {
    file="${HOME}/${1}"
    rsync -r ${file} ${git}/dots/${name} &> /dev/null
    [ $? -ne 0 ] && echo "ERROR: ~/${file} doesn't exist" && return 0
}

title "art"

print "art"
sync

title "bin"

print "bin"
sync

print "art"
sync
title "dots"

print "2bwm"
sync_dots ".config/2bwm/config.h"

print "bash"
sync_dots ".bashrc"
sync_dots ".bash_profile"

print "dunst"
sync_dots ".config/dunst/"

print "nvim"
sync_dots ".config/nvim/"

print "polybar"
sync_dots ".config/polybar/"

print "redshift"
sync_dots ".config/redshift/"

print "wpa_supplicant"
sync_dots ".config/wpa_supplicant"

print "x"
sync_dots ".Xresources"
sync_dots ".xinitrc"

echo
