#!/usr/bin/env bash

old_ctheme=`cat ${HOME}/.colors | head -2 | tail -1 | cut -f2 -d" "`
git="${HOME}/.git/thms"
dir="${HOME}/.themes"
readme=${git}/README.md

preview() {
    sleep 0.5
    urxvtc -geometry 54x9 -e colr -s
    sleep 0.5
    theme=`cat ${HOME}/.colors | head -1 | cut -f2 -d" "`
    mv ${dir}/${theme}/preview.png ${dir}/${theme}/${1}.png  
}

print() {
    echo -e "\n${1}" >> $readme
}

preview "$old_ctheme"
tmp_ctheme=`[[ "$old_ctheme" == "dark" ]] && echo "light" || echo "dark"`
art -q -s
preview "$tmp_ctheme"

cp -r ${dir}/${theme} ${git}

echo "# Themes" > $readme

print "> Wallpapers: [unsplash](https://unsplash.com/)"

for entry in ${git}/*
do
    if [ -d $entry ]
    then
        entry=$(basename $entry) 
        print "### ${entry}"
        print "![${entry} dark](/${entry}/dark.png)"
        print "![${entry} light](/${entry}/light.png)"
    fi
done

art -q -s
