#!/usr/bin/env bash
#
#  //''\ ||  |  //\  ['|']
#  ``--. ||--| ||  |   |  
#  \\__/ ||  |  \\/   .|  
#
# Description:              A minimal screenshot manager
# Dependencies:             imagemagick
# Optionnal dependencies:   notf
# Author:                   gawlk
# Contributors:             none

dir="${HOME}/Pictures/Screenshots"
mkdir -p "$dir" || exit 1

date=$( date +%Y-%m-%d )
time=$( date +%H-%M-%S )

mkdir -p "${dir}/${date}"
shot="${dir}/${date}/${date}-${time}"

for number in 3 2 1
do
    notf "${number}..."
    sleep 1
done

notf "Shot taken !" &> /dev/null || printf '%s\n' "Shot taken !"

sleep 0.1

import -window root "${shot}.png" &
