#!/usr/bin/env bash
#
# Description: 
# Dependency: 

dir="${HOME}/.config/wpa_supplicant"
mkdir -p $dir
card=`ip link | grep 2 | cut -f2 -d" " | sed 's/.$//'`
ssid=`iw dev ${card} link | grep "SSID" | xargs`

case $1 in
    "on")
        [ -n "$ssid" ] && echo "Wifi already on" && exit 0
        #sudo macchanger -r $card
        sudo wpa_supplicant -B -i $card -c $dir/wifi.conf &> /dev/null
        sudo dhcpcd $card &> /dev/null
    ;;
    "off")
        sudo kill `ps aux | grep "wpa_supplicant" | awk '{ print $2 }' | head -1` &> /dev/null
        sudo kill `ps aux | grep "dhcpcd" | awk '{ print $2 }' | head -1` &> /dev/null
    ;;
    "restart")
        wifi off
        sleep 0.2
        wifi on
    ;;
    "ssid")
        [ -z "$ssid" ] && ssid="SSID: None"
        notf "$ssid"
    ;;
    "status")
        [ -z "$ssid" ] && wifi="off" || wifi="on"
        notf "Wifi: $wifi"
    ;;
    "")
        wifi on
    ;;
    *)
        echo "ERROR: Wrong parameter, please try again"
        exit 1
    ;;
esac


