#!/usr/bin/env bash
#
# Description: 
# Dependency: 

dir="${HOME}/.config/wpa_supplicant"
mkdir -p $dir
card=`ip link | grep 2 | cut -f2 -d" " | sed 's/.$//'`

sudo kill `ps aux | grep "wpa_supplicant" | awk '{ print $2 }' | head -1` &> /dev/null
sudo kill `ps aux | grep "dhcpcd" | awk '{ print $2 }' | head -1` &> /dev/null

[ -n "$1" ] && exit 1

sudo wpa_supplicant -B -i $card -c $dir/wifi.conf &> /dev/null
sudo dhcpcd $card &> /dev/null
